"""empty message

Revision ID: 6955a494e1d5
Revises: 8843bbaf0d3d
Create Date: 2018-05-04 11:13:24.200806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6955a494e1d5'
down_revision = '8843bbaf0d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date_created')
    # ### end Alembic commands ###
