"""empty message

Revision ID: 709a863467c7
Revises: 6955a494e1d5
Create Date: 2018-05-05 18:17:30.093861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709a863467c7'
down_revision = '6955a494e1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'complete')
    # ### end Alembic commands ###
