"""empty message

Revision ID: 8843bbaf0d3d
Revises: 589571cf0153
Create Date: 2018-05-03 17:49:00.879346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8843bbaf0d3d'
down_revision = '589571cf0153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('meals', sa.Integer(), nullable=True))
    op.drop_constraint(u'orders_meal_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'meal', ['meals'], ['id'])
    op.drop_column('orders', 'meal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(u'orders_meal_id_fkey', 'orders', 'meal', ['meal_id'], ['id'])
    op.drop_column('orders', 'meals')
    # ### end Alembic commands ###
